spring:
    application:
      name: hello-spring-cloud-admin

    # 服务追踪配置
    zipkin:
      base-url: http://localhost:9411


# 以下为本地配置，启用云配置后删除
server:
  port: 8084



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8887/eureka/

# 健康检查
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["health","info"]
