spring:
  application:
    name: hello-spring-cloud-admin

  # 服务追踪配置
  zipkin:
    base-url: http://localhost:9410
    #开启zipkin
    enabled: true
    #收集追踪信息的比率，如果是0.1则表示只记录10%的追踪数据，如果要全部追踪，设置为1（实际场景不推荐，因为会造成不小的性能消耗）
  sleuth:
    sampler:
      probability: 1

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8886/eureka/

# 健康检查
#management:
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        include: ["health","info"]