spring:
  application:
    name: hello-spring-cloud-web-admin-feign

  # 服务追踪配置
  zipkin:
    base-url: http://localhost:9411
  # 用来模拟UI层配置
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 8866

# feign 自带熔断器，默认是关闭的，需要再配置打开，配置如下
feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8887/eureka/


