spring:
  application:
    name: hello-spring-cloud-web-admin-ribbon

  # 服务追踪配置
  zipkin:
    base-url: http://localhost:9411

  # 用来模拟UI层配置
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 8881

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8887/eureka/