spring:
  application:
    name: hello-spring-cloud-zipkin

  #解决The bean 'characterEncodingFilter', defined in class path resource....
  main:
    allow-bean-definition-overriding: true

  # 添加服务监控-客户端服务地址
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 9411 # 默认端口

#解决IllegalArgumentException: Prometheus requires that all......
management:
  metrics:
    web:
      server:
        auto-time-requests: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8887/eureka/

