spring:
  application:
    name: hello-spring-cloud-zuul

  # 服务追踪配置
  zipkin:
    base-url: http://localhost:9411
    #开启zipkin
    enabled: true
    #收集追踪信息的比率，如果是0.1则表示只记录10%的追踪数据，如果要全部追踪，设置为1（实际场景不推荐，因为会造成不小的性能消耗）
  sleuth:
    sampler:
      probability: 1

server:
  port: 8879

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8887/eureka/

zuul:
  routes:
    #聚合以下两个服务，名称可以随便取（api-a）
    api-a:
      path: /api/a/**
      serviceId: hello-spring-cloud-web-admin-ribbon
    api-b:
      path: /api/b/**
      serviceId: hello-spring-cloud-web-admin-feign