spring:
  application:
    name: hello-spring-cloud-zuul

  # 服务追踪配置
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8879

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8887/eureka/

zuul:
  routes:
    #聚合以下两个服务，名称可以随便取（api-a）
    api-a:
      path: /api/a/**
      serviceId: hello-spring-cloud-web-admin-ribbon
    api-b:
      path: /api/b/**
      serviceId: hello-spring-cloud-web-admin-feign